import os
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from utils.dataloader import get_train_test_loaders, get_cv_train_test_loaders
from utils import model
from utils.model import CustomVGG
from utils.helper import train, evaluate, predict_localize
from utils.constants import NEG_CLASS
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 563)
        MainWindow.setStyleSheet("margin: 0;\n"
"spacing: 0;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setMinimumSize(QtCore.QSize(100, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftMenu.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"\n"
"background-color: rgb(235, 235, 235);\n"
"\n"
"background-color: #23364B;")
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.logoWidget = QtWidgets.QWidget(self.leftMenu)
        self.logoWidget.setObjectName("logoWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.logoWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.logo = QtWidgets.QLabel(self.logoWidget)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setMouseTracking(True)
        self.logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo.setAutoFillBackground(False)
        self.logo.setStyleSheet("color: #fff;")
        self.logo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.verticalLayout_10.addWidget(self.logo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_7.addWidget(self.logoWidget)
        self.pagesWidget = QtWidgets.QWidget(self.leftMenu)
        self.pagesWidget.setStyleSheet("color: #fff;")
        self.pagesWidget.setObjectName("pagesWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pagesWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeWidget = QtWidgets.QWidget(self.pagesWidget)
        self.homeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.homeWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: #245756;")
        self.homeWidget.setObjectName("homeWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.homeWidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.homeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(30, 25))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/feather/home.svg"))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.homeLabel = QtWidgets.QLabel(self.homeWidget)
        self.homeLabel.setStyleSheet("color: #fff;")
        self.homeLabel.setObjectName("homeLabel")
        self.horizontalLayout_6.addWidget(self.homeLabel)
        self.verticalLayout_8.addWidget(self.homeWidget)
        self.aboutWidget = QtWidgets.QWidget(self.pagesWidget)
        self.aboutWidget.setObjectName("aboutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.aboutWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.aboutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(30, 25))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/feather/info.svg"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.aboutLabel = QtWidgets.QLabel(self.aboutWidget)
        self.aboutLabel.setObjectName("aboutLabel")
        self.horizontalLayout_7.addWidget(self.aboutLabel)
        self.verticalLayout_8.addWidget(self.aboutWidget)
        self.statWidget = QtWidgets.QWidget(self.pagesWidget)
        self.statWidget.setObjectName("statWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.statWidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.statWidget)
        self.label_3.setMaximumSize(QtCore.QSize(30, 25))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/feather/activity.svg"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.statLabel = QtWidgets.QLabel(self.statWidget)
        self.statLabel.setObjectName("statLabel")
        self.horizontalLayout_8.addWidget(self.statLabel)
        self.verticalLayout_8.addWidget(self.statWidget)
        self.verticalLayout_7.addWidget(self.pagesWidget)
        self.elseWidget = QtWidgets.QWidget(self.leftMenu)
        self.elseWidget.setObjectName("elseWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.elseWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.elseWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton.setStyleSheet("border: 0;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(22, 22))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_7.addWidget(self.elseWidget)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setToolTip("")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.home_page)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_10 = QtWidgets.QWidget(self.home_page)
        self.widget_10.setStyleSheet("background-color: rgb(39, 36, 87);\n"
"background-color: rgb(76, 76, 76);\n"
"background-color: rgb(36, 87, 86);\n"
"background-color: #295361;")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_23 = QtWidgets.QWidget(self.widget_10)
        self.widget_23.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_23.setStyleSheet("\n"
"background-color: rgb(76, 163, 255);\n"
"\n"
"background-color: #295361;")
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.widget_24 = QtWidgets.QWidget(self.widget_23)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.burgerButton_2 = QtWidgets.QPushButton(self.widget_24)
        self.burgerButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.burgerButton_2.setStyleSheet("border: 0;\n"
"color: #FFF;")
        self.burgerButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/feather/chevron-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.burgerButton_2.setIcon(icon1)
        self.burgerButton_2.setIconSize(QtCore.QSize(20, 20))
        self.burgerButton_2.setObjectName("burgerButton_2")
        self.horizontalLayout_17.addWidget(self.burgerButton_2)
        self.label_24 = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #FFF;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24, 0, QtCore.Qt.AlignVCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_24)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("border: 0;")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/feather/chevron-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_17.addWidget(self.pushButton_2)
        self.horizontalLayout_18.addWidget(self.widget_24)
        self.verticalLayout_17.addWidget(self.widget_23)
        self.photosWidget_1 = QtWidgets.QWidget(self.widget_10)
        self.photosWidget_1.setObjectName("photosWidget_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.photosWidget_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.photosWidget_1)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.photo_1 = QtWidgets.QLabel(self.widget_4)
        self.photo_1.setStyleSheet("border: 2px black solid;\n"
"background-color: rgb(255, 255, 255);")
        self.photo_1.setText("")
        self.photo_1.setObjectName("photo_1")
        self.verticalLayout_11.addWidget(self.photo_1)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_6.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.photosWidget_1)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.photo_2 = QtWidgets.QLabel(self.widget_3)
        self.photo_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo_2.setText("")
        self.photo_2.setObjectName("photo_2")
        self.verticalLayout_12.addWidget(self.photo_2)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_7.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.photosWidget_1)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.photo_3 = QtWidgets.QLabel(self.widget_2)
        self.photo_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo_3.setText("")
        self.photo_3.setObjectName("photo_3")
        self.verticalLayout_13.addWidget(self.photo_3)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_8.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_17.addWidget(self.photosWidget_1)
        self.widget_22 = QtWidgets.QWidget(self.widget_10)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.photosWidget_2 = QtWidgets.QWidget(self.widget_22)
        self.photosWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photosWidget_2.setObjectName("photosWidget_2")
        self.verticalLayout_23.addWidget(self.photosWidget_2)
        self.label_23 = QtWidgets.QLabel(self.widget_22)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_23.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.verticalLayout_17.addWidget(self.widget_22)
        self.widget_7 = QtWidgets.QWidget(self.widget_10)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 47))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadButton = QtWidgets.QPushButton(self.widget_7)
        self.loadButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadButton.setFont(font)
        self.loadButton.setStyleSheet("background-color:#332F2E;\n"
"color: #fff;\n"
"border-radius: 20;")
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton, 0, QtCore.Qt.AlignVCenter)
        self.classifyButton = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classifyButton.sizePolicy().hasHeightForWidth())
        self.classifyButton.setSizePolicy(sizePolicy)
        self.classifyButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.classifyButton.setFont(font)
        self.classifyButton.setStyleSheet("background-color: #332F2E;\n"
"color: #fff;")
        self.classifyButton.setIconSize(QtCore.QSize(17, 17))
        self.classifyButton.setObjectName("classifyButton")
        self.horizontalLayout_3.addWidget(self.classifyButton, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_17.addWidget(self.widget_7)
        self.photosWidget_3 = QtWidgets.QWidget(self.widget_10)
        self.photosWidget_3.setObjectName("photosWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.photosWidget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.photosWidget_3)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.photo_4 = QtWidgets.QLabel(self.widget_8)
        self.photo_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo_4.setText("")
        self.photo_4.setObjectName("photo_4")
        self.verticalLayout_16.addWidget(self.photo_4)
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_9.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.widget_6 = QtWidgets.QWidget(self.photosWidget_3)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.photo_5 = QtWidgets.QLabel(self.widget_6)
        self.photo_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo_5.setText("")
        self.photo_5.setObjectName("photo_5")
        self.verticalLayout_15.addWidget(self.photo_5)
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_10.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.horizontalLayout_4.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.photosWidget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.photo_6 = QtWidgets.QLabel(self.widget_5)
        self.photo_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.photo_6.setText("")
        self.photo_6.setObjectName("photo_6")
        self.verticalLayout_14.addWidget(self.photo_6)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_11.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"background-color: rgb(0, 0, 0);\n"
"color: #fff;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_17.addWidget(self.photosWidget_3)
        self.horizontalLayout_10.addWidget(self.widget_10)
        self.secMenu = QtWidgets.QWidget(self.home_page)
        self.secMenu.setMinimumSize(QtCore.QSize(100, 0))
        self.secMenu.setMaximumSize(QtCore.QSize(177, 16777215))
        self.secMenu.setStyleSheet("background-color: #23364B;\n"
"display: flex;\n"
"flex-direction: column;\n"
"align-items: center;\n"
"align-content: center;")
        self.secMenu.setObjectName("secMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.secMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instContainer = QtWidgets.QWidget(self.secMenu)
        self.instContainer.setObjectName("instContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.instContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instWidget = QtWidgets.QWidget(self.instContainer)
        self.instWidget.setStyleSheet("background-color: transparent;\n"
"color: #fff;")
        self.instWidget.setObjectName("instWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.instWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.instTitle = QtWidgets.QLabel(self.instWidget)
        self.instTitle.setObjectName("instTitle")
        self.verticalLayout_5.addWidget(self.instTitle, 0, QtCore.Qt.AlignTop)
        self.inst_1 = QtWidgets.QLabel(self.instWidget)
        self.inst_1.setWordWrap(True)
        self.inst_1.setObjectName("inst_1")
        self.verticalLayout_5.addWidget(self.inst_1)
        self.inst_3 = QtWidgets.QLabel(self.instWidget)
        self.inst_3.setWordWrap(True)
        self.inst_3.setObjectName("inst_3")
        self.verticalLayout_5.addWidget(self.inst_3)
        self.inst_4 = QtWidgets.QLabel(self.instWidget)
        self.inst_4.setWordWrap(True)
        self.inst_4.setObjectName("inst_4")
        self.verticalLayout_5.addWidget(self.inst_4)
        self.inst_2 = QtWidgets.QLabel(self.instWidget)
        self.inst_2.setWordWrap(True)
        self.inst_2.setObjectName("inst_2")
        self.verticalLayout_5.addWidget(self.inst_2)
        self.verticalLayout_2.addWidget(self.instWidget, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.instContainer)
        self.optionsContainer = QtWidgets.QWidget(self.secMenu)
        self.optionsContainer.setObjectName("optionsContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optionsContainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.optionsWidget = QtWidgets.QWidget(self.optionsContainer)
        self.optionsWidget.setStyleSheet("background-color: transparent;\n"
"color: #fff;")
        self.optionsWidget.setObjectName("optionsWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.optionsWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.optionsTitle = QtWidgets.QLabel(self.optionsWidget)
        self.optionsTitle.setObjectName("optionsTitle")
        self.verticalLayout_4.addWidget(self.optionsTitle)
        self.checkBox_1 = QtWidgets.QCheckBox(self.optionsWidget)
        self.checkBox_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_1.setAutoFillBackground(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.verticalLayout_4.addWidget(self.checkBox_1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.optionsWidget)
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.verticalLayout_3.addWidget(self.optionsWidget, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.optionsContainer)
        self.horizontalLayout_10.addWidget(self.secMenu)
        self.stackedWidget.addWidget(self.home_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.about_page)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_9 = QtWidgets.QWidget(self.about_page)
        self.widget_9.setStyleSheet("background-color: #295361;\n"
"color: #fff;")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.header = QtWidgets.QWidget(self.widget_9)
        self.header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.header.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(76, 163, 255);\n"
"background-color: #295361;\n"
"")
        self.header.setObjectName("header")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_25 = QtWidgets.QWidget(self.header)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.burgerButton_3 = QtWidgets.QPushButton(self.widget_25)
        self.burgerButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.burgerButton_3.setStyleSheet("border: 0;")
        self.burgerButton_3.setText("")
        self.burgerButton_3.setIcon(icon1)
        self.burgerButton_3.setIconSize(QtCore.QSize(20, 20))
        self.burgerButton_3.setObjectName("burgerButton_3")
        self.horizontalLayout_19.addWidget(self.burgerButton_3)
        self.label_25 = QtWidgets.QLabel(self.widget_25)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_24.addWidget(self.widget_25)
        self.verticalLayout_6.addWidget(self.header)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_18.setContentsMargins(20, 20, -1, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_12 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_18.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.verticalLayout_6.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_19.setContentsMargins(20, 20, -1, 97)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_19.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget_12)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.verticalLayout_6.addWidget(self.widget_12)
        self.horizontalLayout_13.addWidget(self.widget_9)
        self.stackedWidget.addWidget(self.about_page)
        self.stat_page = QtWidgets.QWidget()
        self.stat_page.setObjectName("stat_page")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.stat_page)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_16 = QtWidgets.QWidget(self.stat_page)
        self.widget_16.setStyleSheet("background-color: #295361;\n"
"color: #fff;")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget = QtWidgets.QWidget(self.widget_16)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setStyleSheet("background-color: rgb(76, 163, 255);\n"
"background-color: #295361;")
        self.widget.setObjectName("widget")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_13 = QtWidgets.QWidget(self.widget)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("border: 0;\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.label_5 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_25.addWidget(self.widget_13)
        self.verticalLayout_20.addWidget(self.widget)
        self.widget_15 = QtWidgets.QWidget(self.widget_16)
        self.widget_15.setStyleSheet("color: #000;")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_18 = QtWidgets.QWidget(self.widget_15)
        self.widget_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: #fff;\n"
"border-radius: 17;\n"
"background-color: #265D80")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_21.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.horizontalLayout_14.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_15)
        self.widget_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 17;\n"
"color: #fff;\n"
"background-color: #265D80;")
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_22.addWidget(self.label_20)
        self.horizontalLayout_14.addWidget(self.widget_19)
        self.verticalLayout_20.addWidget(self.widget_15)
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setStyleSheet("color: #000;")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_20.setObjectName("widget_20")
        self.label_21 = QtWidgets.QLabel(self.widget_20)
        self.label_21.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.widget_20)
        self.widget_21 = QtWidgets.QWidget(self.widget_17)
        self.widget_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_21.setObjectName("widget_21")
        self.label_22 = QtWidgets.QLabel(self.widget_21)
        self.label_22.setGeometry(QtCore.QRect(30, 40, 47, 13))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.widget_21)
        self.verticalLayout_20.addWidget(self.widget_17)
        self.widget_14 = QtWidgets.QWidget(self.widget_16)
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_20.addWidget(self.widget_14)
        self.horizontalLayout_16.addWidget(self.widget_16)
        self.stackedWidget.addWidget(self.stat_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo.setText(_translate("MainWindow", "Visual inspection"))
        self.homeLabel.setText(_translate("MainWindow", "Home"))
        self.aboutLabel.setText(_translate("MainWindow", "Infos"))
        self.statLabel.setText(_translate("MainWindow", "Statistics"))
        self.label_24.setText(_translate("MainWindow", "Home"))
        self.label_6.setText(_translate("MainWindow", "OK"))
        self.label_7.setText(_translate("MainWindow", "OK"))
        self.label_8.setText(_translate("MainWindow", "OK"))
        self.label_23.setText(_translate("MainWindow", "OK"))
        self.loadButton.setText(_translate("MainWindow", "Open File"))
        self.classifyButton.setText(_translate("MainWindow", "Classify"))
        self.label_9.setText(_translate("MainWindow", "OK"))
        self.label_10.setText(_translate("MainWindow", "OK"))
        self.label_11.setText(_translate("MainWindow", "OK"))
        self.instTitle.setText(_translate("MainWindow", "Instructions to start"))
        self.inst_1.setText(_translate("MainWindow", "1. Click Browse file"))
        self.inst_3.setText(_translate("MainWindow", "2. Choose options"))
        self.inst_4.setText(_translate("MainWindow", "3. Click Classify"))
        self.inst_2.setText(_translate("MainWindow", "4. Explore features in the menu bar"))
        self.optionsTitle.setText(_translate("MainWindow", "Options"))
        self.checkBox_1.setText(_translate("MainWindow", "  Heatmap"))
        self.checkBox_4.setText(_translate("MainWindow", "  CheckBox"))
        self.label_25.setText(_translate("MainWindow", "Infos"))
        self.label_12.setText(_translate("MainWindow", "Problem"))
        self.label_13.setText(_translate("MainWindow", "Quality control is one of the most important factors in manufacturing systems. Performing a manual inspection on each product is costly in both time and effort, producing bottlenecks and delaying production. In many cases, defects can be easily missed by the human eye—even by industry experts—resulting in decreased quality of an individual component or in a defective final product that must be scrapped. Defect rates can often increase with more complex manufacturing systems.\n"
"\n"
"Having an automatic system to detect anomalies and differences in elements is crucial for the quality inspection process in any automatic manufacturing system. This applies to any industry that needs to be able to detect defects or variations within components or small particles."))
        self.label_14.setText(_translate("MainWindow", "Solution"))
        self.label_15.setText(_translate("MainWindow", "Concept les freres’s VI application uses computer vision with deep-learning models to detect and identify different types of abnormalities in sardiine cans. It takes 7 images of a sardine can from different positions, preprocesses them, classify them, and then round a bounding box around the area that contains defects.\n"
""))
        self.label_5.setText(_translate("MainWindow", "Statistics"))
        self.label_17.setText(_translate("MainWindow", "Defected"))
        self.label_19.setText(_translate("MainWindow", "200"))
        self.label_18.setText(_translate("MainWindow", "Non-Defected"))
        self.label_20.setText(_translate("MainWindow", "300"))
        self.label_21.setText(_translate("MainWindow", "Plot1"))
        self.label_22.setText(_translate("MainWindow", "Plot2"))
import AppStuff.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
